manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: cnboggs 
      url-base: https://github.com/cnboggs
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-pmw3389-driver
      remote: cnboggs
      revision: pmw3389
  #   - name: pmw3389_zephyr_driver
  #     remote: cnboggs
  #     revision: debug
  #     path: modules/pmw3389
  self:
    path: config
