manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cnboggs 
      url-base: https://github.com/cnboggs
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: pmw3389_zephyr_driver
      remote: cnboggs 
      revision: zephyr 
      path: modules/pmw3389
  self:
    path: config
