manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: teamspatzenhirn
      url-base: https://github.com/teamspatzenhirn
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: pmw3389_zephyr_driver
      remote: teamspatzenhirn
      revision: 837e0ab2182d8748b46bf188f03c7dde4d4e0328
      path: modules/pmw3389
  self:
    path: config
